name: Actions Workflow

on: 
  push:
  pull_request:
    types: [closed, assigned, reopened, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA                                     # commit id
          echo $GITHUB_REPOSITORY                              # name of our repository 
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
      - name: simple JS Action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
